// server/services/ingestionService.js — Document ingestion pipeline
// Upload → Extract → Chunk → Store in PostgreSQL

const { query, getClient } = require('../db/pool');
const chunkText = require('../utils/chunker');
const chat = require('../utils/llm3');

/**
 * Create a new notebook
 * @param {string} title - Notebook title
 * @returns {Promise<{id: string, title: string}>}
 */
async function createNotebook(title = 'Untitled Notebook') {
    const result = await query(
        'INSERT INTO notebooks (title) VALUES ($1) RETURNING id, title, created_at',
        [title]
    );
    return result.rows[0];
}

/**
 * Get a notebook by ID, including its documents
 * @param {string} notebookId
 * @returns {Promise<object|null>}
 */
async function getNotebook(notebookId) {
    const nbResult = await query(
        'SELECT * FROM notebooks WHERE id = $1',
        [notebookId]
    );
    if (nbResult.rows.length === 0) return null;

    const docsResult = await query(
        'SELECT id, filename, original_name, file_type, file_size, status, page_count, word_count, chunk_count, summary, created_at FROM documents WHERE notebook_id = $1 ORDER BY created_at DESC',
        [notebookId]
    );

    return {
        ...nbResult.rows[0],
        documents: docsResult.rows
    };
}

/**
 * Full ingestion pipeline: take extracted text and store as searchable chunks
 * 
 * @param {string} textContent - Extracted text from document
 * @param {string} filename - Original filename
 * @param {object} options
 * @param {string} options.notebookId - Existing notebook ID (creates new if not provided)
 * @param {string} options.fileType - File type (pdf, docx, txt)
 * @param {number} options.fileSize - File size in bytes
 * @param {string} options.notebookTitle - Title for new notebook
 * @returns {Promise<{notebookId: string, documentId: string, chunkCount: number, summary: string}>}
 */
async function ingestDocument(textContent, filename, options = {}) {
    const { notebookId, fileType, fileSize, notebookTitle } = options;
    
    const client = await getClient();
    
    try {
        await client.query('BEGIN');

        // 1. Create or use existing notebook
        let nbId = notebookId;
        if (!nbId) {
            const title = notebookTitle || filename.replace(/\.[^/.]+$/, '');
            const nbResult = await client.query(
                'INSERT INTO notebooks (title) VALUES ($1) RETURNING id',
                [title]
            );
            nbId = nbResult.rows[0].id;
            console.log(`📓 Created notebook: ${nbId}`);
        }

        // 2. Create document record (status: processing)
        const docResult = await client.query(
            `INSERT INTO documents (notebook_id, filename, original_name, file_type, file_size, status)
             VALUES ($1, $2, $3, $4, $5, 'processing')
             RETURNING id`,
            [nbId, filename, filename, fileType || 'unknown', fileSize || 0]
        );
        const documentId = docResult.rows[0].id;
        console.log(`📄 Created document: ${documentId}`);

        // 3. Chunk the text
        console.log(`🔪 Chunking text (${textContent.length} chars)...`);
        const chunks = chunkText(textContent);
        console.log(`   → ${chunks.length} chunks created`);

        // 4. Batch insert chunks (tsvector auto-generated by trigger)
        if (chunks.length > 0) {
            const values = [];
            const placeholders = [];
            let paramIndex = 1;

            for (const chunk of chunks) {
                placeholders.push(
                    `($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3}, $${paramIndex + 4}, $${paramIndex + 5})`
                );
                values.push(
                    documentId,
                    chunk.content,
                    chunk.chunkIndex,
                    chunk.pageNumber,
                    chunk.wordCount,
                    JSON.stringify({})
                );
                paramIndex += 6;
            }

            await client.query(
                `INSERT INTO chunks (document_id, content, chunk_index, page_number, word_count, metadata)
                 VALUES ${placeholders.join(', ')}`,
                values
            );
            console.log(`   → ${chunks.length} chunks stored in DB`);
        }

        // 5. Calculate word count
        const totalWords = chunks.reduce((sum, c) => sum + c.wordCount, 0);

        // 6. Generate summary via LLM
        let summary = '';
        try {
            console.log('🧠 Generating document summary...');
            const summaryResponse = await chat.call([
                {
                    role: 'system',
                    content: `You are an expert summarizer. Create a concise 3-5 sentence summary of the document. Focus on the main topics and key takeaways. Be direct and informative.`
                },
                {
                    role: 'user',
                    content: `Summarize this document:\n\n${textContent.substring(0, 6000)}`
                }
            ], { max_tokens: 500 });
            summary = summaryResponse.content || '';
        } catch (err) {
            console.warn('⚠️ Summary generation failed:', err.message);
            summary = 'Summary generation unavailable.';
        }

        // 7. Update document status to ready
        await client.query(
            `UPDATE documents 
             SET status = 'ready', 
                 word_count = $1, 
                 chunk_count = $2, 
                 summary = $3,
                 page_count = $4
             WHERE id = $5`,
            [totalWords, chunks.length, summary, Math.ceil(totalWords / 500), documentId]
        );

        await client.query('COMMIT');
        console.log(`✅ Ingestion complete: ${chunks.length} chunks, ${totalWords} words`);

        return {
            notebookId: nbId,
            documentId,
            chunkCount: chunks.length,
            wordCount: totalWords,
            summary,
            status: 'ready'
        };

    } catch (err) {
        await client.query('ROLLBACK');
        console.error('❌ Ingestion failed:', err.message);

        // Try to mark document as errored if it was created
        try {
            await query(
                `UPDATE documents SET status = 'error', error_message = $1 WHERE filename = $2 AND status = 'processing'`,
                [err.message, filename]
            );
        } catch (_) { /* ignore */ }

        throw err;
    } finally {
        client.release();
    }
}

/**
 * Delete a document and all its chunks
 * @param {string} documentId
 */
async function deleteDocument(documentId) {
    await query('DELETE FROM documents WHERE id = $1', [documentId]);
    console.log(`🗑️ Deleted document: ${documentId}`);
}

/**
 * Get documents for a notebook
 * @param {string} notebookId
 * @returns {Promise<Array>}
 */
async function getDocuments(notebookId) {
    const result = await query(
        `SELECT id, filename, original_name, file_type, file_size, status, 
                page_count, word_count, chunk_count, summary, created_at
         FROM documents 
         WHERE notebook_id = $1 
         ORDER BY created_at DESC`,
        [notebookId]
    );
    return result.rows;
}

/**
 * Get document status
 * @param {string} documentId
 * @returns {Promise<object|null>}
 */
async function getDocumentStatus(documentId) {
    const result = await query(
        'SELECT id, status, chunk_count, word_count, error_message FROM documents WHERE id = $1',
        [documentId]
    );
    return result.rows[0] || null;
}

module.exports = {
    createNotebook,
    getNotebook,
    ingestDocument,
    deleteDocument,
    getDocuments,
    getDocumentStatus
};
